version: 2
template:
  name: Upgrade to Toolchain
  description: 
    $ref: description.md
  header: ![](toolchain.svg)

toolchain:
  name: "{{projectName}}"
  generator: migration-engine
  template:
    v1-projectId: "{{projectId}}"
    scheduledDate: "{{scheduledDate}}"
  required: 
     - deploy
     - repo

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: "{{projectName}}"
      repo_url: "{{projectRepoUrl}}"
      type: link
      has_issues: true    

  build:
    service_id: pipeline
    parameters:
      name: "{{projectName}}"
      v1-projectId: "{{projectId}}"
      services: ["repo"]
      configuration: 
      content: "{{pipelineContent}}"
      execute: false
      env:
        REPO: "repo"
      source:
        environment: "{{pipelineEnv}}"
        version: v1
        pipelineUrl: "{{pipelineUrl}}"
        projectUrl: "{{projectUrl}}"
        showLink: true 

  webide:
    service_id: orion

form:
  githubpublic:
    schema:
      $ref: github.json
    parameters:
      repo_url: "{{projectRepoUrl}}"
